name: Auto Update on flexconfigs Self-Hosted Runner

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  auto-update:
    runs-on: [self-hosted, flexconfigs-label]  # Match the label of your self-hosted runner

    steps:
      - name: Fix File Ownership
        run: |
          sudo chown -R actions:actions /home/actions/actions-runner/_work/flexconfigs
          sudo chmod -R u+w /home/actions/actions-runner/_work/flexconfigs

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Kill PHP and Server Services
        run: |
          docker compose kill mysql php server

      - name: Pull Latest Changes
        working-directory: ./code
        run: |
          git config --global --add safe.directory $PWD
          git pull

      - name: Run Composer
        run: |
          docker compose run --rm --build --remove-orphans composer

      - name: Start Docker Services
        env:
          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
          MYSQL_USER: ${{ vars.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

        run: |
          docker compose up mysql php server --build --remove-orphans -d

      - name: Set Permissions for Storage
        run: |
          sudo chown -R www-data:www-data ./code/storage/
          sudo chmod -R 777 ./code/storage

      - name: Create .env file
        run: |
          cp ./code/.env.example ./code/.env

      - name: Run Artisan Commands
        run: |
          docker compose run --rm artisan key:generate
          docker compose run --rm artisan config:clear

      - name: Install npm Dependencies and Build
        run: |
          docker compose run --rm npm npm install
          docker compose run --rm npm npm run build

      - name: Run Database Migrations
        run: |
          docker compose run --rm artisan migrate 
